/*
  GENERATED by `npm run bake:voice`. Do not edit.

  A TypeScript module rather than a JSON file beside the audio, and that is the
  decision the whole timing contract rests on: this is compiled into the bundle,
  so it cannot 404. The mp3s can, and when they do the round is identical minus
  the sound - same beats, same subtitles, for the same length of time - because
  nothing about the script ever consults the audio.

  `hash` is of the `spoken` string each file was rendered from. `voice.test.ts`
  compares it against `INSTRUCTOR_LINES`, which is what makes it impossible to
  change the wizard's words and leave the audio saying the old ones.
*/

export type VoiceLine = {
  /** Served from `public/`, so it is a root-relative URL rather than an import. */
  file: string
  /** Seconds, measured off the encoded file. The speech beat is derived from it. */
  duration: number
  /** First 16 hex of sha256 over the exact spoken string. */
  hash: string
}

export const VOICE = {
  voice: "bm_george",
  /** British English phonemes. Kokoro only WARNS if this disagrees with the voice. */
  lang: "b",
  /** Durations are only valid for the speed they were rendered at. */
  speed: 1,
  lines: [
    {
      "file": "/voice/instructor-0.mp3",
      "duration": 3.925,
      "hash": "aa458de7118dacc3"
    },
    {
      "file": "/voice/instructor-1.mp3",
      "duration": 4.975,
      "hash": "67c2c6df7c869aae"
    }
  ] as const satisfies readonly VoiceLine[],
} as const
