/*
  GENERATED by `npm run bake:voice`. Do not edit.

  A TypeScript module rather than a JSON file beside the audio, and that is the
  decision the whole timing contract rests on: this is compiled into the bundle,
  so it cannot 404. The mp3s can, and when they do the round is identical minus
  the sound - same beats, same subtitles, for the same length of time - because
  nothing about the script ever consults the audio.

  `hash` is of the spoken string each file was rendered from. `voice.test.ts`
  compares it against the copy, which is what makes it impossible to change the
  wizard's words and leave the audio saying the old ones.

  `words` comes from Kokoro's own per-phoneme duration prediction rather than
  from measuring the output or estimating from word length - see
  `tools/voice/speak.py`. The numbers are what the vocoder was TOLD to produce,
  so they are exact by construction.
*/

export type VoiceWord = {
  text: string
  /** Seconds from the start of this clip. */
  start: number
  end: number
}

export type VoiceClip = {
  /** Served from `public/`, so a root-relative URL rather than an import. */
  file: string
  /** Seconds, measured off the encoded file. */
  duration: number
  /** Every word, in order, with the time it is spoken. */
  words: readonly VoiceWord[]
  /** First 16 hex of sha256 over the exact spoken string. */
  hash: string
}

/** A card segment, which is one clause and the form that illustrates it. */
export type VoiceSegment = VoiceClip & { card: number; index: number }

export const VOICE = {
  voice: "bm_lewis",
  /** British English phonemes. Kokoro only WARNS if this disagrees with the voice. */
  lang: "b",
  /** Durations are only valid for the speed they were rendered at. */
  speed: 1,
  /** What the instructor says on the way in. */
  lines: [
    {
      "file": "/voice/instructor-0.mp3",
      "duration": 3.875,
      "words": [
        {
          "text": "Ah,",
          "start": 0.4,
          "end": 0.688
        },
        {
          "text": "an",
          "start": 0.688,
          "end": 0.775
        },
        {
          "text": "apprentice!",
          "start": 0.775,
          "end": 1.688
        },
        {
          "text": "Welcome",
          "start": 1.688,
          "end": 2.15
        },
        {
          "text": "to",
          "start": 2.15,
          "end": 2.325
        },
        {
          "text": "A.I.",
          "start": 2.325,
          "end": 2.837
        },
        {
          "text": "training.",
          "start": 2.837,
          "end": 3.775
        }
      ],
      "hash": "aa458de7118dacc3"
    },
    {
      "file": "/voice/instructor-1.mp3",
      "duration": 5.075,
      "words": [
        {
          "text": "Two",
          "start": 0.35,
          "end": 0.563
        },
        {
          "text": "short",
          "start": 0.563,
          "end": 0.9
        },
        {
          "text": "scrolls,",
          "start": 0.9,
          "end": 1.625
        },
        {
          "text": "then",
          "start": 1.625,
          "end": 1.825
        },
        {
          "text": "one",
          "start": 1.825,
          "end": 2.05
        },
        {
          "text": "question.",
          "start": 2.05,
          "end": 2.975
        },
        {
          "text": "You",
          "start": 2.975,
          "end": 3.112
        },
        {
          "text": "will",
          "start": 3.112,
          "end": 3.25
        },
        {
          "text": "answer",
          "start": 3.25,
          "end": 3.6
        },
        {
          "text": "it",
          "start": 3.6,
          "end": 3.75
        },
        {
          "text": "with",
          "start": 3.75,
          "end": 3.888
        },
        {
          "text": "an",
          "start": 3.888,
          "end": 4.037
        },
        {
          "text": "arrow.",
          "start": 4.037,
          "end": 4.975
        }
      ],
      "hash": "67c2c6df7c869aae"
    }
  ] as const satisfies readonly VoiceClip[],
  /** The cards, narrated one clause at a time. */
  segments: [
    {
      "file": "/voice/card-0-0.mp3",
      "card": 0,
      "index": 0,
      "duration": 6.4,
      "words": [
        {
          "text": "Behold:",
          "start": 0.35,
          "end": 1.262
        },
        {
          "text": "a",
          "start": 1.262,
          "end": 1.35
        },
        {
          "text": "machine",
          "start": 1.35,
          "end": 1.85
        },
        {
          "text": "that",
          "start": 1.85,
          "end": 1.975
        },
        {
          "text": "read",
          "start": 1.975,
          "end": 2.263
        },
        {
          "text": "very",
          "start": 2.263,
          "end": 2.587
        },
        {
          "text": "nearly",
          "start": 2.587,
          "end": 3.013
        },
        {
          "text": "everything,",
          "start": 3.013,
          "end": 3.875
        },
        {
          "text": "and",
          "start": 3.875,
          "end": 3.987
        },
        {
          "text": "was",
          "start": 3.987,
          "end": 4.162
        },
        {
          "text": "told",
          "start": 4.162,
          "end": 4.625
        },
        {
          "text": "what",
          "start": 4.625,
          "end": 4.838
        },
        {
          "text": "none",
          "start": 4.838,
          "end": 5.088
        },
        {
          "text": "of",
          "start": 5.088,
          "end": 5.2
        },
        {
          "text": "it",
          "start": 5.2,
          "end": 5.35
        },
        {
          "text": "means.",
          "start": 5.35,
          "end": 6.3
        }
      ],
      "hash": "00fa6a21a5a218b9"
    },
    {
      "file": "/voice/card-0-1.mp3",
      "card": 0,
      "index": 1,
      "duration": 5.6,
      "words": [
        {
          "text": "Give",
          "start": 0.35,
          "end": 0.487
        },
        {
          "text": "it",
          "start": 0.487,
          "end": 0.6
        },
        {
          "text": "a",
          "start": 0.6,
          "end": 0.713
        },
        {
          "text": "library",
          "start": 0.713,
          "end": 1.363
        },
        {
          "text": "and",
          "start": 1.363,
          "end": 1.488
        },
        {
          "text": "it",
          "start": 1.488,
          "end": 1.563
        },
        {
          "text": "will",
          "start": 1.563,
          "end": 1.75
        },
        {
          "text": "fetch;",
          "start": 1.75,
          "end": 2.638
        },
        {
          "text": "give",
          "start": 2.638,
          "end": 2.813
        },
        {
          "text": "it",
          "start": 2.813,
          "end": 2.938
        },
        {
          "text": "time",
          "start": 2.938,
          "end": 3.425
        },
        {
          "text": "and",
          "start": 3.425,
          "end": 3.538
        },
        {
          "text": "it",
          "start": 3.538,
          "end": 3.612
        },
        {
          "text": "will",
          "start": 3.612,
          "end": 3.775
        },
        {
          "text": "work",
          "start": 3.775,
          "end": 4.05
        },
        {
          "text": "step",
          "start": 4.05,
          "end": 4.35
        },
        {
          "text": "by",
          "start": 4.35,
          "end": 4.588
        },
        {
          "text": "step.",
          "start": 4.588,
          "end": 5.5
        }
      ],
      "hash": "b2a3d47fae7d4b5c"
    },
    {
      "file": "/voice/card-0-2.mp3",
      "card": 0,
      "index": 2,
      "duration": 8.15,
      "words": [
        {
          "text": "But",
          "start": 0.325,
          "end": 0.45
        },
        {
          "text": "underneath",
          "start": 0.45,
          "end": 1.05
        },
        {
          "text": "is",
          "start": 1.05,
          "end": 1.212
        },
        {
          "text": "one",
          "start": 1.212,
          "end": 1.488
        },
        {
          "text": "trick,",
          "start": 1.488,
          "end": 1.9
        },
        {
          "text": "always:",
          "start": 1.9,
          "end": 2.888
        },
        {
          "text": "guess",
          "start": 2.888,
          "end": 3.175
        },
        {
          "text": "what",
          "start": 3.175,
          "end": 3.325
        },
        {
          "text": "comes",
          "start": 3.325,
          "end": 3.65
        },
        {
          "text": "next,",
          "start": 3.65,
          "end": 4.375
        },
        {
          "text": "and",
          "start": 4.375,
          "end": 4.5
        },
        {
          "text": "from",
          "start": 4.5,
          "end": 4.65
        },
        {
          "text": "all",
          "start": 4.65,
          "end": 4.875
        },
        {
          "text": "that",
          "start": 4.875,
          "end": 5.138
        },
        {
          "text": "reading,",
          "start": 5.138,
          "end": 5.75
        },
        {
          "text": "it",
          "start": 5.75,
          "end": 5.912
        },
        {
          "text": "guesses",
          "start": 5.912,
          "end": 6.425
        },
        {
          "text": "uncannily",
          "start": 6.425,
          "end": 7.175
        },
        {
          "text": "well.",
          "start": 7.175,
          "end": 8.05
        }
      ],
      "hash": "623a3fabbc81eceb"
    },
    {
      "file": "/voice/card-1-0.mp3",
      "card": 1,
      "index": 0,
      "duration": 9.25,
      "words": [
        {
          "text": "No",
          "start": 0.4,
          "end": 0.637
        },
        {
          "text": "wizard",
          "start": 0.637,
          "end": 1.063
        },
        {
          "text": "wrote",
          "start": 1.063,
          "end": 1.313
        },
        {
          "text": "its",
          "start": 1.313,
          "end": 1.512
        },
        {
          "text": "rules.",
          "start": 1.512,
          "end": 2.45
        },
        {
          "text": "We",
          "start": 2.45,
          "end": 2.6
        },
        {
          "text": "hid",
          "start": 2.6,
          "end": 2.813
        },
        {
          "text": "what",
          "start": 2.813,
          "end": 2.95
        },
        {
          "text": "came",
          "start": 2.95,
          "end": 3.237
        },
        {
          "text": "next",
          "start": 3.237,
          "end": 3.675
        },
        {
          "text": "and",
          "start": 3.675,
          "end": 3.813
        },
        {
          "text": "corrected",
          "start": 3.813,
          "end": 4.325
        },
        {
          "text": "it,",
          "start": 4.325,
          "end": 4.825
        },
        {
          "text": "a",
          "start": 4.825,
          "end": 4.938
        },
        {
          "text": "trillion",
          "start": 4.938,
          "end": 5.438
        },
        {
          "text": "times",
          "start": 5.438,
          "end": 5.85
        },
        {
          "text": "over,",
          "start": 5.85,
          "end": 6.5
        },
        {
          "text": "until",
          "start": 6.5,
          "end": 6.85
        },
        {
          "text": "the",
          "start": 6.85,
          "end": 6.987
        },
        {
          "text": "guessing",
          "start": 6.987,
          "end": 7.487
        },
        {
          "text": "turned",
          "start": 7.487,
          "end": 7.95
        },
        {
          "text": "uncanny.",
          "start": 7.95,
          "end": 9.15
        }
      ],
      "hash": "db38a6d10e0bdc94"
    },
    {
      "file": "/voice/card-1-1.mp3",
      "card": 1,
      "index": 1,
      "duration": 5.45,
      "words": [
        {
          "text": "Then",
          "start": 0.35,
          "end": 0.512
        },
        {
          "text": "we",
          "start": 0.512,
          "end": 0.625
        },
        {
          "text": "trained",
          "start": 0.625,
          "end": 0.963
        },
        {
          "text": "it",
          "start": 0.963,
          "end": 1.05
        },
        {
          "text": "again,",
          "start": 1.05,
          "end": 1.65
        },
        {
          "text": "by",
          "start": 1.65,
          "end": 1.825
        },
        {
          "text": "hand,",
          "start": 1.825,
          "end": 2.575
        },
        {
          "text": "to",
          "start": 2.575,
          "end": 2.7
        },
        {
          "text": "do",
          "start": 2.7,
          "end": 2.862
        },
        {
          "text": "as",
          "start": 2.862,
          "end": 2.975
        },
        {
          "text": "you",
          "start": 2.975,
          "end": 3.138
        },
        {
          "text": "ask",
          "start": 3.138,
          "end": 3.563
        },
        {
          "text": "rather",
          "start": 3.563,
          "end": 3.925
        },
        {
          "text": "than",
          "start": 3.925,
          "end": 4.125
        },
        {
          "text": "ramble",
          "start": 4.125,
          "end": 4.575
        },
        {
          "text": "on.",
          "start": 4.575,
          "end": 5.35
        }
      ],
      "hash": "4ecba54636529b03"
    },
    {
      "file": "/voice/card-1-2.mp3",
      "card": 1,
      "index": 2,
      "duration": 6.075,
      "words": [
        {
          "text": "So",
          "start": 0.375,
          "end": 0.512
        },
        {
          "text": "it",
          "start": 0.512,
          "end": 0.6
        },
        {
          "text": "gives",
          "start": 0.6,
          "end": 0.85
        },
        {
          "text": "you",
          "start": 0.85,
          "end": 0.975
        },
        {
          "text": "what",
          "start": 0.975,
          "end": 1.163
        },
        {
          "text": "usually",
          "start": 1.163,
          "end": 1.625
        },
        {
          "text": "follows,",
          "start": 1.625,
          "end": 2.225
        },
        {
          "text": "not",
          "start": 2.225,
          "end": 2.425
        },
        {
          "text": "what",
          "start": 2.425,
          "end": 2.575
        },
        {
          "text": "is",
          "start": 2.575,
          "end": 2.75
        },
        {
          "text": "true.",
          "start": 2.75,
          "end": 3.563
        },
        {
          "text": "Confident,",
          "start": 3.563,
          "end": 4.325
        },
        {
          "text": "and",
          "start": 4.325,
          "end": 4.513
        },
        {
          "text": "perfectly",
          "start": 4.513,
          "end": 5.063
        },
        {
          "text": "wrong.",
          "start": 5.063,
          "end": 5.975
        }
      ],
      "hash": "63771b73ee810027"
    }
  ] as const satisfies readonly VoiceSegment[],
  /** The quiz question, read when the board brings it in. */
  question: {
    "file": "/voice/question.mp3",
    "duration": 4.4,
    "words": [
      {
        "text": "So",
        "start": 0.375,
        "end": 0.563
      },
      {
        "text": "tell",
        "start": 0.563,
        "end": 0.813
      },
      {
        "text": "me,",
        "start": 0.813,
        "end": 0.975
      },
      {
        "text": "apprentice.",
        "start": 0.975,
        "end": 1.95
      },
      {
        "text": "Underneath",
        "start": 1.95,
        "end": 2.475
      },
      {
        "text": "it",
        "start": 2.475,
        "end": 2.6
      },
      {
        "text": "all,",
        "start": 2.6,
        "end": 3.05
      },
      {
        "text": "what",
        "start": 3.05,
        "end": 3.225
      },
      {
        "text": "does",
        "start": 3.225,
        "end": 3.4
      },
      {
        "text": "it",
        "start": 3.4,
        "end": 3.525
      },
      {
        "text": "do?",
        "start": 3.525,
        "end": 4.3
      }
    ],
    "hash": "7d8d5ad25a77994f"
  } as const satisfies VoiceClip,
} as const
